[theme]
base = "light"
primaryColor = "#4f46e5"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false
